cart/urls.py
from django.urls import path
from .views import cart_detail_view, add_to_cart_view, remove_from_cart,\
    clear_cart, add_to_favorites, favorites_list

app_name = 'cart'

urlpatterns = [
    path('cart_detail/', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear/', clear_cart, name='clear_cart'),
    path('favoriteAdd/<int:product_id>', add_to_favorites, name='add_to_favorites'),
    path('favoritelist/', favorites_list, name='favorites_list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('account/', include('allauth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('contactus/', include('contactus.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payments.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('aboutme/', TemplateView.as_view(template_name="aboutme.html"), name='aboutme'),
    path('rules/', TemplateView.as_view(template_name="rules.html"), name='rules'),
    path("__debug__/", include("debug_toolbar.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import order_create_view

app_name = 'orders'
urlpatterns = [
    path('create/', order_create_view, name='order_create'),
]

shop/urls.py
from django.urls import path
from .views import product_detail_view, search_product_view, all_product_view, \
    CommentEdit, comment_reply_view, admin_awareness_check

app_name = 'shop'

urlpatterns = [
    path('', all_product_view, name='product_list'),
    path('<int:pk>/', product_detail_view, name='product_detail'),
    path('search/', search_product_view, name='search_product_view'),

    # path('order products/<int:pk>/', order_products_view, name='order_products'),
    path('comment update/<int:pk>/', CommentEdit.as_view(), name='edit_comment'),
    path('commentreply/', comment_reply_view, name='comment_reply'),
    path('admin_awareness_check/', admin_awareness_check, name='admin_awareness_check'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class AddToCartForm(forms.Form):
    """    A FORM TO ADD NEW PRODUCT TO CART   """

    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 25)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    color = forms.CharField()
    size = forms.CharField()

    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.utils.translation import gettext as _
from django.contrib import messages

from cart.cart import Cart
from .favorite import Favorite
from .forms import AddToCartForm
from shop.models import Product


@require_POST
def add_to_cart_view(request, product_id):
    """ GET ID, COLOR, SIZE AND QUANTITY OF A PRODUCT FROM ADD FORM TO BE ADDED TO CART"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddToCartForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        color = cleaned_data['color']
        size = cleaned_data['size']
        replace_current_quantity = False

        cart.add(product, size, color, quantity, replace_current_quantity)
    else:
        messages.warning(request, 'Oops , did you forgot to choose size and color !!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def cart_detail_view(request):
    """ SHOW CART DETAIL """

    cart = Cart(request)
    for item in cart:
        item['product_update_quantity_form'] = AddToCartForm(initial={
            'quantity': item['quantity'],
            'inplace': True,
        })
    return render(request, 'cart/cart_detail.html', {
        'cart': cart,
    })


def remove_from_cart(request, product_id):
    """ REMOVE AN ID FROM CART  """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def clear_cart(request):
    """ CLEAR CART FROM SESSION """
    cart = Cart(request)

    if cart.is_empty():
        messages.warning(request, _('you have nothing in cart'))

    else:
        cart.clear()
        messages.success(request, _('your cart get empy'))

    return redirect('cart:cart_detail')



def add_to_favorites(request, product_id):
    """ add/remove , to/from favorite """
    get_object_or_404(Product, id=product_id)
    favorite = Favorite(request)
    favorite.add(product_id)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def favorites_list(request):
    favorite = Favorite(request)
    if favorite.is_empty() or False:
        messages.success(request, _('your favorites list is empty '))

    product_ids = favorite
    favorites = Product.objects.filter(id__in=product_ids)

    return render(request, 'shop/product_list.html', {'products': favorites})

cart/templates/cart/cart_sidebar.html
{% load i18n %}
{% load static %}

<!-- Mini Cart Start -->
<aside class="mini-cart" id="miniCart">
    <div class="mini-cart-wrapper">
        <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
        <div class="mini-cart-inner">
            <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">{% translate 'Cart' %}</h3>
            <div class="mini-cart__content">
                <ul class="mini-cart__list text-right">
                {% if cart %}
                    {% for item in cart %}
                        <li class="mini-cart__product d-flex justify-content-between">
                            <div class="mini-cart__product__image">
                                <a href="{% url 'shop:product_detail'  item.product_obj.id %}">

                                    {% if product.image %}
                                        <img class="m-auto"  src="{{ item.product_obj.image.url }}" alt="">
                                    {% else %}
                                        <img src="{% static 'img/default-cloth-image.jpg' %}"
                                             alt="Product image">
                                    {% endif %}
                                </a>
                            </div>
                            <div class="mini-cart__product__content pt-2">
                                <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                    <a href="{% url 'shop:product_detail'  item.product_obj.id %}">{{ item.product_obj.title }}</a>
                                    <a href="{% url 'cart:remove_from_cart' item.product_obj.id %}" class="">
                                        &#10060;
                                    </a>
                                </span>
                                <span class="mini-cart__product__quantity">
                                    <span>{{ item.product_obj.price_by_offer }}</span> &#215; <span>{{ item.quantity }}</span>
                                </span>
                            </div>
                        </li>
                    {% endfor %}
                {% endif %}
                </ul>
                <div class="mini-cart__total">
                    <span>{% translate 'Total' %}</span>
                    <span class="ammount">{{ cart.get_total_price }} {% translate '$' %}</span>
                </div>
                <div class="mini-cart__buttons">
                    <a href="{% url 'cart:cart_detail' %}"
                       class="btn btn-fullwidth btn-bg-sand mb--20">{% translate 'Go to cart' %}</a>
                    {% if  cart.is_empty %}
                        <a href="{% url 'orders:order_create' %}"
                           class="btn btn-fullwidth btn-bg-sand">{% translate 'Checkout' %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</aside>
<!-- Mini Cart End -->

cart/templates/cart/wishlist.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}

{% block page_title %} {% trans 'wish list' %}{% endblock %}

{% block content %}
    {% load i18n %}

    <!-- Main Wrapper Start -->
    <div class="wrapper">
        <!-- Main Content Wrapper Start -->
        <div class="main-content-wrapper container-fluid">
            <div class="shop-page-wrapper shop-fullwidth">
                <div class="container">
                    <div class="row mb--50">
                        <div class="col-12">
                            <div class="shop-toolbar">
                                <div class="container row align-items-center">
                                    <div class="col-lg-12 mb-md--50 mb-xs--10">
                                        <div class="shop-toolbar__left d-flex align-items-sm-center align-items-start flex-sm-row flex-column">
                                            <p class="product-pages"> Favorits
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container-fluid shop-products">
                    <div class="row">
                        <div class="col-12">
                            <div class="tab-content" id="product-tab-content">
                                <div class="tab-pane fade show active" id="nav-all">
                                    <div class="row xxl-block-grid-6 grid-space-20">
                                        {% if favorites %}


                                            {% for favorite in favorites %}
                                                <div class="col-xl-3 col-md-4 col-sm-6 mb--50">
                                                    <div class="ShoppingYar-product">
                                                        <div class="product-inner">
                                                            <figure class="product-image">
                                                                <a href="{{ favorite.get_absolute_url }}">
                                                                    {% if favorite.image %}
                                                                        <img src="{{ favorite.image.url }}"
                                                                             alt="Products">
                                                                    {% endif %}
                                                                </a>
                                                                <div class="ShoppingYar-product-action">
                                                                    <div class="product-action d-flex"> <img class="flaticon flaticon-like"
                                                                                                 src="{% static 'img/heart2.png' %}">
                                                                        <a id="favorite"
                                                                           href="{% url 'cart:add_to_favorites' favorite.id %}">

                                                                            <div class="ShoppingYar-product-action">
                                                                                <div class="product-action d-flex">


                                                                                            <img class="flaticon flaticon-like"
                                                                                                 src="{% static 'img/heart3.png' %}">



                                                                                </div>
                                                                            </div>
                                                                        </a>
                                                                    </div>
                                                                </div>
                                                                <span class="product-badge">تخفیف ویژه</span>
                                                            </figure>
                                                            <div class="product-info">
                                                                <h3 class="product-title mb--15">
                                                                    <a href="{{ favorite.get_absolute_url }}">{{ favorite.title }}</a>

                                                                </h3>
                                                                <div class="product-price-wrapper mb--30">
                                                                    <span class="money">{{ favorite.price }} {% translate '$' %}</span>
                                                                </div>
                                                                <form action="{% url 'cart:add_to_cart' favorite.id %}"
                                                                      method="POST">
                                                                    {% csrf_token %}
                                                                    <input type="hidden" class="quantity-input"
                                                                           name="quantity" id="qty" value="1" min="1"
                                                                           max="30">
                                                                    <div class="quantity-wrapper">
                                                                        <button type="submit"
                                                                                class="btn btn-small btn-bg-red btn-color-white btn-hover-2">
                                                                            {% trans 'Add to Cart' %}
                                                                        </button>
                                                                    </div>
                                                                </form>
                                                                {#                                                    <a href="cart.html" class="btn btn-small btn-bg-sand btn-color-dark px-3">اضافه کردن به سبد خرید</a>#}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <nav class="pagination-wrap mt--35 mt-md--25 pb-5">
                                <ul class="pagination">

                                    {% if page_obj.has_previous %}
                                        <li><a href="?page={{ page_obj.previous_page_number }}"
                                               class="prev page-number">

                                            previous</a>
                                        </li>

                                    {% endif %}

                                    {#                                    <li><span class="current page-number">{{ page_obj.number }}</span></li>#}

                                    {% for page in page_obj.paginator.page_range %}

                                        <li><a href="?page={{ page }}" class="page-number"> {{ page }}</a></li>

                                    {% endfor %}



                                    {% if page_obj.has_next %}
                                        <li><a href="?page={{ page_obj.next_page_number }}" class="next page-number">

                                            next</a></li>
                                    {% endif %}

                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content Wrapper Start -->


        <!-- Search form Popup Start -->
        <div class="searchform__popup" id="searchForm">
            <a href="{% url 'shop:search_product_view' %}" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="searchform__body">
                <p>در باکس زیر عبارت خود را وارد کنید</p>
                <form method="POST" action="{% url 'shop:search_product_view' %}">
                    {% csrf_token %}
                    <input type="text" name="text" id="popup-search" class="searchform__input"
                           placeholder="جستجو در بین محصولات...">
                    <button type="submit" class="searchform__submit"><i
                            class="flaticon flaticon-magnifying-glass-icon"></i></button>
                </form>
            </div>
        </div>
        <!-- Search form Popup End -->

        {% include 'cart/cart_sidebar.html' %}

        <!-- Global Overlay Start -->
        <div class="ShoppingYar-global-overlay"></div>
        <!-- Global Overlay End -->

    </div>
    <!-- Main Wrapper End -->



{% endblock %}