accounts/urls.py
from django.urls import path
from .views import profile_view, EditUserInformation, redirect_user

app_name = 'accounts'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('editt/<int:pk>/', EditUserInformation.as_view(), name='edit_user_information'),
    path('redirect/', redirect_user, name='redirect_user'),
]

cart/urls.py
from django.urls import path
from .views import cart_detail_view, add_to_cart_view, remove_from_cart,\
    clear_cart, add_to_favorites, favorites_list

app_name = 'cart'

urlpatterns = [
    path('cart_detail/', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear/', clear_cart, name='clear_cart'),
    path('favoriteAdd/<int:product_id>', add_to_favorites, name='add_to_favorites'),
    path('favoritelist/', favorites_list, name='favorites_list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('account/', include('allauth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('contactus/', include('contactus.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payments.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('aboutme/', TemplateView.as_view(template_name="aboutme.html"), name='aboutme'),
    path('rules/', TemplateView.as_view(template_name="rules.html"), name='rules'),
    path("__debug__/", include("debug_toolbar.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contactus/urls.py
from django.urls import path
from .views import user_to_admin_contact, all_new_contact, AdminAnswerContact

app_name = 'contactus'

urlpatterns = [
    path('usercontact/', user_to_admin_contact, name='user_to_admin_contact'),
    path('NewContact/', all_new_contact, name='all_new_contact'),
    path('AdminContact/<int:pk>', AdminAnswerContact.as_view(), name='admin_answer_contact'),
]

shop/urls.py
from django.urls import path
from .views import product_detail_view, search_product_view, all_product_view, \
    CommentEdit, comment_reply_view, admin_awareness_check

app_name = 'shop'

urlpatterns = [
    path('', all_product_view, name='product_list'),
    path('<int:pk>/', product_detail_view, name='product_detail'),
    path('search/', search_product_view, name='search_product_view'),

    # path('order products/<int:pk>/', order_products_view, name='order_products'),
    path('comment update/<int:pk>/', CommentEdit.as_view(), name='edit_comment'),
    path('commentreply/', comment_reply_view, name='comment_reply'),
    path('admin_awareness_check/', admin_awareness_check, name='admin_awareness_check'),
]

accounts/models.py
from urllib import request
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    """ this model make user fields editable"""
    number = models.IntegerField(null=True, blank=True, error_messages='', verbose_name=_('Phone Number'))
    image = models.ImageField(blank=True, upload_to='image/users_image', verbose_name=_('Image'))

    def get_absolute_url(self):
        return redirect(request.GET.get('next', '/'))

accounts/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationFrom(UserCreationForm):
    """ this is a custom form for user sign up """

    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields
        widgets = {'password': forms.PasswordInput(), }


class CustomUserChangeForm(UserChangeForm):
    """ this is a custom created user form """

    class Meta:
        model = get_user_model()
        fields = UserChangeForm.Meta.fields
        widgets = {'password': forms.PasswordInput(), }


class UserInformationChangeForm(forms.ModelForm):
    """ this is a form to get changed information from user """
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', 'number', 'image')

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views import generic

from accounts.forms import UserInformationChangeForm
from accounts.models import CustomUser
from cart.favorite import Favorite
from shop.models import Product


@login_required
def profile_view(request):
    """ THIS VIEW SHOW THE USER PROFILE   """
    user = request.user
    
    """ getting user favorites information"""
    product_ids = Favorite(request)
    favorites = Product.objects.filter(id__in=product_ids)

    """ getting user'S comments """
    comments = user.comments.all()
    reply_comments = user.reply.all()

    """ getting user order and order items information"""
    orders = user.orders.prefetch_related('items').all()

    return render(request, 'accounts/profile.html',
                  {'favorites': favorites,
                   'comments': comments,
                   'orders': orders,
                   'reply_comments': reply_comments,
                   })


class EditUserInformation(generic.UpdateView):
    """ THIS IS VIEW FOR EDIT USER INFORMATIONS   """
    model = CustomUser
    form_class = UserInformationChangeForm
    template_name = 'accounts/edit_profile.html'
    success_url = reverse_lazy('accounts:profile')


def redirect_user(request):
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

accounts/templates/accounts/edit_profile.html
<!doctype html>
<html lang="en">
{% load i18n %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/edit_profile.css' %}">
    <title> {% translate "Edit information's" %} </title>


</head>
<body>

<div class="content">

    <div class="holder">

        <div>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <button type="submit"> Submit</button>
            </form>

            <a href="{% url 'shop:product_list' %}">{% translate 'Home' %}</a>
        </div>

    </div>


</div>


</body>
</html>

accounts/templates/accounts/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LOGIN</title>
</head>
<body>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button> submit </button>
</form>

</body>
</html>

accounts/templates/accounts/profile.html
<!doctype html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{% static 'img/clothing-shop-logo.jpg' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/default-cloth-image.jpg' %}">


    <link rel="stylesheet" href="{% static 'css/profile.css' %}" type="text/css">

    <title>{% trans 'About Me' %}</title>

</head>
<body>

<header id="header">
    {% if messages %}
        <div class="container">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>

    {% endif %}

    <div class="right_holder">
        <div>
            <h2><a href="{% url 'cart:cart_detail' %}">{% trans 'cart' %}</a></h2>
            <br>
            {% if not cart.is_empty %}
                {% for item in cart %}
                    <p><a href="{% url 'shop:product_detail' item.product_obj.id %}"> {{ item.product_obj.title }}</a>
                    </p>
                {% endfor %}
            {% endif %}
        </div>

        <div>
            <h2>{% trans 'Favorites' %}  </h2>
            <br>
            {% for favorite in favorites %}
                <p><a href="{% url 'shop:product_detail' favorite.id %}"> {{ favorite.title }}</a></p>
            {% endfor %}
        </div>

        <div>
            <h2> {% trans 'Orders' %}</h2>
            <br>
            {% if orders %}
                {% for order in orders %}
                    {{ order.date_time_created }} :
                    {% if  order.is_paid %}
                        paid
                    {% else %}
                        not paid
                    {% endif %}

                    <p style="color: white">
                        {% for item in order.items.all %}
                            {{ item.product }}<br>
                            quantity : {{ item.quantity }}<br>
                            color : {{ item.color }}<br>
                            size : {{ item.size }}<br>
                            price : {{ item.price }}
                            <br>-----------------------------<br>

                        {% endfor %}

                    </p>
                    <br><br>
                {% endfor %}
            {% endif %}


        </div>


    </div>


    <div class="left_holder">
        <div>
            {% if user.image %}
                <img class="user_image" src="{{ user.image.url }}" alt="image">
            {% else %}
                <img src="{% static 'img/userlogo.png' %}" alt="image" class="user_image">
            {% endif %}
        </div>

        <div>
            <h2>{% translate ' Welcome to your panel deer ' %} {{ user.username }} </h2>
            <p>  {% translate ' You joined us at ' %}: {{ user.date_joined }}</p>
            <p>  {% translate ' First name ' %}: {{ user.first_name }}</p>
            <p> {% translate ' Last Name ' %}: {{ user.last_name }}</p>

            <p>   {% translate 'Email' %}: {{ user.email }}</p>
            <p>   {% translate 'Number' %}: {{ user.number }}</p>
            {% if user.is_staff %}
                <p> STATUS : STAFF</p>
                <p><a href="../../admin">{% translate 'Panel Admin' %}  </a></p>
                <p>
                    <a href="{% url 'contactus:all_new_contact' %}" class="mainmenu__link">
                        <span class="mm-text"> {% translate 'Notifications' %} </span>
                    </a>
                </p>
                <p><a href="../../rosetta/"> {% trans 'Translation' %} </a></p>
            {% else %}
                <p> STATUS : USER </p>
            {% endif %}

            <p>
                <a href="{% url 'accounts:edit_user_information' user.id %}"> {% translate "Edit Informations" %} </a>
            </p>

            <p>
                <a href=" {% url 'account_change_password' %}"> {% translate "Change Password" %} </a>
            </p>

            <p>
                <a href=" {% url 'account_reset_password' %}"> {% translate "forgot Password" %} </a>
            </p>

            <p>
                <a href="{% url 'account_logout' %}"> {% translate "logout" %}</a>
            </p>
        </div>

        <div>
            <h2> {% trans 'Your Comments' %}</h2>
            {% for comment in comments %}
                {% if comment.product.image %}
                    <img src="{{ comment.product.image.url }}">
                {% else %}
                    <img src="{% static 'img/default-cloth-image.jpg' %}"
                         alt="Product image">
                {% endif %}
                <p><a href="{% url 'shop:product_detail' comment.product.id %}">{{ comment.text }}</a></p>
            {% endfor %}

        </div>

        <div>
            <h2> {% trans 'Your replies Comments' %}</h2>
            {% for reply_comment in reply_comments %}

                {% if reply_comment.reply_product.image %}
                    <img src="{{ reply_comment.reply_product.image.url }}">
                {% else %}
                    <img src="{% static 'img/default-cloth-image.jpg' %}"
                         alt="Product image">
                {% endif %}
                <p> comment :{{ reply_comment.reply_comment.text }} </p>

                <p>
                    <a href="{% url 'shop:product_detail' reply_comment.reply_product.id %}">
                        {% trans 'you replied ' %}: {{ reply_comment.text }}
                    </a>
                </p>
            {% endfor %}


        </div>

    </div>


    <a href="{% url 'shop:product_list' %}" class="back_to_home"> {% trans 'Back To Home' %} </a>
</header>


</body>
</html>