accounts/urls.py
from django.urls import path
from .views import profile_view, EditUserInformation, redirect_user

app_name = 'accounts'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('editt/<int:pk>/', EditUserInformation.as_view(), name='edit_user_information'),
    path('redirect/', redirect_user, name='redirect_user'),
]

cart/urls.py
from django.urls import path
from .views import cart_detail_view, add_to_cart_view, remove_from_cart,\
    clear_cart, add_to_favorites, favorites_list

app_name = 'cart'

urlpatterns = [
    path('cart_detail/', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear/', clear_cart, name='clear_cart'),
    path('favoriteAdd/<int:product_id>', add_to_favorites, name='add_to_favorites'),
    path('favoritelist/', favorites_list, name='favorites_list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('account/', include('allauth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('contactus/', include('contactus.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payments.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('aboutme/', TemplateView.as_view(template_name="aboutme.html"), name='aboutme'),
    path('rules/', TemplateView.as_view(template_name="rules.html"), name='rules'),
    path("__debug__/", include("debug_toolbar.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contactus/urls.py
from django.urls import path
from .views import user_to_admin_contact, all_new_contact, AdminAnswerContact

app_name = 'contactus'

urlpatterns = [
    path('usercontact/', user_to_admin_contact, name='user_to_admin_contact'),
    path('NewContact/', all_new_contact, name='all_new_contact'),
    path('AdminContact/<int:pk>', AdminAnswerContact.as_view(), name='admin_answer_contact'),
]

shop/urls.py
from django.urls import path
from .views import product_detail_view, search_product_view, all_product_view, \
    CommentEdit, comment_reply_view, admin_awareness_check

app_name = 'shop'

urlpatterns = [
    path('', all_product_view, name='product_list'),
    path('<int:pk>/', product_detail_view, name='product_detail'),
    path('search/', search_product_view, name='search_product_view'),

    # path('order products/<int:pk>/', order_products_view, name='order_products'),
    path('comment update/<int:pk>/', CommentEdit.as_view(), name='edit_comment'),
    path('commentreply/', comment_reply_view, name='comment_reply'),
    path('admin_awareness_check/', admin_awareness_check, name='admin_awareness_check'),
]

templates/_base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block page_title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'img/clothing-shop-logo.jpg' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/default-cloth-image.jpg' %}">

    <!-- ************************* CSS Files ************************* -->

    <link rel="stylesheet" href="{% static 'css/_base.css' %}">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">

    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- ************************* js Files ************************* -->
    <script src='{% static 'js/_base.js' %}'> </script>



</head>

<body dir='rtl'>


<!-- Header Start -->
<header class="header" style="background-color: rgba(27,75,33,0.65); color: white">
    <div class="header-inner fixed-header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-9 col-lg-8 col-5 col-xs-0 col-none col-sm-block p-0">
                    <nav class="main-navigation">
                        <div class="site-branding" style="margin-right: 30px;">

                            <figure class="logo--normal d-none d-sm-block">
                                <img class="px-10" src="{% static 'img/clothing-shop-logo.jpg' %}"
                                     style="height: 100px;max-height: 150px; width: 200px; margin:1px -100px -15px 10px;"
                                     alt="Logo">
                            </figure>

                        </div>
                        <div class="mainmenu-nav d-none d-lg-block w-100 pr-3">
                            <ul class="mainmenu d-lg-flex jusity-content-end jusity-content-lg-start pt-4">
                                <li class="mainmenu__item menu-item-has-children active">
                                    <a href="{% url 'shop:product_list' %}" class="mainmenu__link">
                                        <span class="mm-text">{% translate 'Home' %}</span>
                                    </a>
                                </li>

                                <li class="mainmenu__item">
                                    {% if user.is_staff %}
                                        <a href="{% url 'contactus:all_new_contact' %}"
                                           class="mainmenu__link header-toolbar__btn  mini-cart-btn">

                                            <span class="mm-text">{% translate ' notifications ' %}</span>
                                            <sup class="mini-cart-count"
                                                 style="width: 40%;">{{ contact|length }},{{ admin_awareness|length }}</sup>
                                        </a>

                                        <a href="/admin" class="mainmenu__link">
                                            <span class="mm-text">{% translate 'Admin Panel' %}</span>
                                        </a>

                                    {% else %}
                                        <a href="{% url 'contactus:user_to_admin_contact' %}" class="mainmenu__link">
                                            <span class="mm-text">{% translate 'contact us' %}</span>
                                        </a>
                                    {% endif %}

                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="col-xl-3 col-lg-4 col-sm-7 col-4 p-0">
                    <ul style="width: 500px; padding-left:20px; " class="header-toolbar">
                        <li class="header-toolbar__item">
                            <a href="#searchForm" class="header-toolbar__btn toolbar-btn">

                                <img src="{% static 'img/search.jpg' %}" style="width: 30px; height: 30px">
                            </a>
                        </li>
                        <li class="header-toolbar__item">
                            <a href="{% url 'cart:favorites_list' %}"
                               class="header-toolbar__btn mx-4 header-toolbar__btn mini-cart-btn">
                                {% trans "favorites list" %}
                                <sup class="mini-cart-count">{{ favorites|length }}</sup>
                            </a>
                        </li>

                        <a href="#miniCart" class="header-toolbar__btn toolbar-btn mini-cart-btn base_cart"
                           style="margin-left: 20px">
                            {% translate "cart" %}
                            <sup class="mini-cart-count">{{ cart|length }}</sup>
                        </a>

                        <li class="header-toolbar__item user-info" style="margin-left:30px;">
                            {% if user.is_authenticated %}
                                <a href="{% url 'accounts:profile' %}"
                                   class="header-toolbar__btn">{{ user.username }}</a>
                            {% else %}
                                <i class=""> {% translate 'LOGIN ' %}</i>
                            {% endif %}

                            <ul class="user-info-menu">
                                {% if user.is_authenticated %}
                                    <li style="transition: 1s;">
                                        <a class="text-right"
                                           href="{% url 'account_logout' %}">{% translate 'Logout' %}</a>
                                    </li>
                                    <li>
                                        <a class="text-right"
                                           href="{% url 'accounts:profile' %}">{% translate 'Profile' %}</a>


                                    </li>
                                {% else %}
                                    <li>
                                        <a class="text-right"
                                           href="{% url 'account_login' %}">{% translate 'Login' %}</a>
                                    </li>
                                    <li>
                                        <a class="text-right"
                                           href="{% url 'account_signup' %}">{% translate 'Signup' %}</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="mobile-menu"></div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Header End -->

{% block messages %}

{% endblock %}
{% if messages %}
    <div class="container">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" style="text-align: center">{{ message }}</div>
        {% endfor %}
    </div>

{% endif %}

<!-- Search form Popup Start -->
<div class="searchform__popup" id="searchForm">
    <a href="{% url 'shop:search_product_view' %}" class="btn-close">
        <img src="{% static 'img/icons8-cross.gif' %}" alt="cancel">
    </a>

    <div class="searchform__body">
        <p>{% translate ' type your letters , then push enter' %} </p>
        <form method="POST" action="{% url 'shop:search_product_view' %}">
            {% csrf_token %}
            <input type="text" name="text" id="popup-search" class="searchform__input"
                   placeholder={% translate ' search product' %}>
            <button type="submit" class="searchform__submit"></button>
        </form>
    </div>
</div>
<!-- Search form Popup End -->
{% block content %}


{% endblock %}

{% include 'footer.html' %}

<!-- ************************* JS Files ************************* -->

<!-- jQuery JS -->
<script src="{% static 'js/vendor.js' %}"></script>

<!-- Main JS -->
<script src="{% static 'js/main.js' %}"></script>

<!-- _base JS -->
<script src="{% static 'js/_base.js' %}"></script>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->

</body>
</html>

templates/aboutme.html
<!doctype html>
<html lang="en">
{% load static %}
{% load i18n %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <meta name="description" content="{% trans 'this a clothing shop' %}">
    <meta name="keywords" content="web developer, Python-Django, professional development">


    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/aboutme.css' %}">

    <link rel="shortcut icon" href="{% static 'img/iconA.png' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/iconA.png' %}">

    <title>{% trans 'About Me' %}</title>

</head>
<body>
<div class="container">
    <h1>About Me</h1>
    <p>Hello, my name is ALi Ghorbani. I am a web developer with 1 year of experience in the industry.
        I have a passion for projects that let me do some new experiences,
        I am improving my skills in Python-Django.</p>
    <p>
        I am also committed to continuous learning and professional development to stay updated with the latest trends
        and technologies in my field.</p>
    <p>Feel free to contact me at " alighorbanimail@gmail.com " for any inquiries or collaboration opportunities.
        I am always open to new challenges and exciting projects!</p>

    <h4> more contact way : </h4>

    <div class="telegram contact">
        <img src="{% static 'img/telegram_logo.png' %}">
        <p class="contact-p"> @AliGhorbani_Ali</p>
    </div>

    <div class="phone contact">
        <img src="{% static 'img/phone.png' %}">
        <p class="contact-p">+98 09215994828 </p>
    </div>

    <div class="github contact">
        <img src="{% static 'img/github.png' %}">
        <p class="contact-p">hubgitali </p>

    </div>


    <a href="{% url 'shop:product_list' %}"> {% trans 'Back to Home' %} </a>
</div>


</body>
</html>

templates/footer.html
{% load static %}
{% load i18n %}

<!-- Footer Start-->
<footer class="footer">
    <div class="footer-top bg-color ptb--50" data-bg-color="#f6f6f6">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="footer-widget mb--50">
                        <div class="textwidget">
                            <img src="{% static 'img/iconA.png' %}" alt="Logo">
                            <a href="{% url 'aboutme' %}"> {% translate 'Created by ALi / About me' %}  </a>
                        </div>
                    </div>
                    <div class="footer-widget mb--50 pb--1">
                        <ul class="footer-menu">

                            <br>
                            <br>
                            <li>
                                <a href="{% url 'rules' %}">
                                    <img height="12%" width="13%" src="{% static 'img/Rules.png' %} ">
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-widget">
                        {% translate 'All Rights Reserved' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer End-->

templates/rules.html
<!doctype html>
<html lang="en">
{% load static %}
{% load i18n %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{% static 'img/iconA.png' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/iconA.png' %}">
    <link rel="stylesheet" href="{% static 'css/rules.css' %}">

    <title>{% trans 'Rules And Policies' %}</title>

</head>
<body>

<header class="header">


</header>

<a href="{% url 'shop:product_list' %}"> {% translate 'Back To Home' %}  </a>
<div class="content">

    <div class="content_holder">

        <div class="rules_img">
            <img src="{% static 'img/Rules.png' %}">
        </div>


        <div class="text_holder">
            <p class="policies "> What are Policies?
                The general statements that guide thinking and channel energy toward a particular direction are known as
                Policies.
                Policies are a type of Standing Plan and they provide a basis for interpreting strategy.
                A manager uses policies at his discretion.
                E.g. Decisions taken under recruitment policy can be in the case of recruiting employees for a new
                division,
                such as whether to recruit from the existing employees or to explore other external sources of
                recruitment,
                various policies under it regarding the salary structure, etc.
                A policy is used by organizations as a guide that avoids confusion and provides a structured and unified
                framework.


            </p>

            <p class="rules "> What are Rules?
                Specific statements that inform what must and must not be done are known as Rules.
                They are formed to maintain, regulate and control the working environment.
                They are rigid and do not allow flexibility.
                If rules are violated, then strict disciplinary actions are taken.
                It reflects decisions that certain actions must and must not be taken.
                They are the simplest type of plan which do not require changes from time to time.</p>

        </div>



    </div>


</div>


<footer class="footer">
</footer>

</body>
</html>

templates/topheader.html
{% load i18n %}

<div class="breadcrumb-area bg-color ptb--10" data-bg-color="#f6f6f6">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                    <h1 class="page-title">{{ header_name }}</h1>
                </div>
            </div>
        </div>
    </div>
</div>