cart/urls.py
from django.urls import path
from .views import cart_detail_view, add_to_cart_view, remove_from_cart,\
    clear_cart, add_to_favorites, favorites_list

app_name = 'cart'

urlpatterns = [
    path('cart_detail/', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear/', clear_cart, name='clear_cart'),
    path('favoriteAdd/<int:product_id>', add_to_favorites, name='add_to_favorites'),
    path('favoritelist/', favorites_list, name='favorites_list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('account/', include('allauth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('contactus/', include('contactus.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payments.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('aboutme/', TemplateView.as_view(template_name="aboutme.html"), name='aboutme'),
    path('rules/', TemplateView.as_view(template_name="rules.html"), name='rules'),
    path("__debug__/", include("debug_toolbar.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contactus/urls.py
from django.urls import path
from .views import user_to_admin_contact, all_new_contact, AdminAnswerContact

app_name = 'contactus'

urlpatterns = [
    path('usercontact/', user_to_admin_contact, name='user_to_admin_contact'),
    path('NewContact/', all_new_contact, name='all_new_contact'),
    path('AdminContact/<int:pk>', AdminAnswerContact.as_view(), name='admin_answer_contact'),
]

shop/urls.py
from django.urls import path
from .views import product_detail_view, search_product_view, all_product_view, \
    CommentEdit, comment_reply_view, admin_awareness_check

app_name = 'shop'

urlpatterns = [
    path('', all_product_view, name='product_list'),
    path('<int:pk>/', product_detail_view, name='product_detail'),
    path('search/', search_product_view, name='search_product_view'),

    # path('order products/<int:pk>/', order_products_view, name='order_products'),
    path('comment update/<int:pk>/', CommentEdit.as_view(), name='edit_comment'),
    path('commentreply/', comment_reply_view, name='comment_reply'),
    path('admin_awareness_check/', admin_awareness_check, name='admin_awareness_check'),
]

contactus/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model


class ContactUs(models.Model):
    """     stores the user and admin conversation as 'contact us'     """

    class Meta:
        verbose_name = _("Contact Us")
        verbose_name_plural = _("Contacts Us")

    user = models.ForeignKey(get_user_model(), related_name='contactus',
                             on_delete=models.CASCADE, verbose_name=_("User Name"))
    user_text = models.TextField(_('user message'), max_length='255', )
    admin_text = models.TextField(_('admin message'), blank=True, max_length='255', )
    is_new = models.BooleanField(default=True, verbose_name=_('new'))
    user_sent_date_time = models.TimeField(auto_now_add=True, verbose_name=_('send at'))
    admin_sent_date_time = models.TimeField(auto_now=True, verbose_name=_('answers at'))

    def get_absolute_url(self):
        return reverse('contactus:all_new_contact')

contactus/forms.py
from django import forms

from .models import ContactUs


class ContactForm(forms.Form):
    user_txt = forms.CharField(max_length=255, help_text=' how we can help you ', )
    admin_txt = forms.CharField(max_length=255, required=False, )
    # widgets = {admin_txt: forms.HiddenInput(), }


class UserContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ('user_text',)


class AdminContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['admin_text', 'is_new', ]

contactus/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.decorators import login_required

from .forms import UserContactForm, AdminContactForm
from .models import ContactUs
from accounts.models import CustomUser


@login_required
def user_to_admin_contact(request):
    """ this view gets a message from a user """

    user = get_object_or_404(CustomUser, pk=request.user.id)

    contact = user.contactus.all()
    if request.method == 'POST':
        form = UserContactForm(request.POST)
        if form.is_valid():
            form.cleaned_data
            cleaned_data = form.cleaned_data
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Your Message Was Successfully Send ,please wait ,'
                                      'Our admins will answer you as soon as possible')
        else:
            messages.error(request, 'Your Message Was not Sent ,'
                                    ' Make sure You send message correctly')

    return render(request, 'contactus/contact_us.html', {"contact": contact})


def all_new_contact(request):
    """ this view shows all new messages from users to admin """
    new_contacts = ContactUs.objects.filter(is_new=True)
    if not new_contacts:
        messages.success(request, 'All Contact message was Answered , No more to do ')

    return render(request, 'contactus/user_new_contact.html', {"new_contacts": new_contacts})


class AdminAnswerContact(generic.UpdateView):
    """ this view gets answer from admin for user contact   """
    template_name = 'contactus/admin_contact.html'
    model = ContactUs
    form_class = AdminContactForm
    context_object_name = 'contact'

contactus/templates/contactus/admin_contact.html
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{% static 'img/iconA.png' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/iconA.png' %}">

    <title>{% trans 'contact us' %}</title>

    <style>
        body {
            text-align: center;

        }

        .header {
            margin-bottom: 10px;
            color: white;
        }

        .header > h1 {
            background-color: #0f74a8;
            border-radius: 10px;
            padding: 4px;

        }

        .header > ul {
            list-style: none;
        }

        .header > .alert {
            color: red;
        }

        .header > .alert-success {
            color: red !important;
        }

        .header > .alert-error {
            color: orangered;
        }


        .content {
            min-height: 500px;
            width: 50%;
            margin: 0 auto;
            border-radius: 5px;
            box-shadow: 0 0 10px;
            padding-top: 8px;
            background-image: url({% static 'img/WallpapersNew.jpg' %});
        }

        .content_holder {
            padding: 2px 4px;
            box-shadow: #0E2231 0 0 10px;
            margin: auto;
            width: 90%;
            min-height: 500px;
            color: white !important;
            overflow: hidden;
            border-radius: 3px;
            font-size: 22px;
        }

        .content_holder > .admin {
            float: right;
            width: 25%;
            height: 40px;
            text-align: center;
            padding-top: 10px;
            border-radius: 2px 2px 2px 20px;
        {#background-color: #76d02c;#} margin-bottom: 20px;
            border-bottom: 2px solid black;
            color: red;
        }

        .content_holder > .user {
            color: orangered;
            border: 0 solid transparent;
            float: left;
            width: 20%;
            height: 40px;
            text-align: center;
            padding-top: 10px;
            border-radius: 2px 2px 20px 2px;
        {#background-color: #1e7e34;#} border-bottom: 2px solid black;

        }

        .text_holder {
            border: 2px solid transparent;
            margin-top: 15%;
            font-size: 21px;
            width: 100%;
            min-height: 500px;
        }

        .user_text {
            color: black;
            margin-right: 80%;
            border-bottom: 1px dashed darkblue;
            padding: 2px;
            border-radius: 4px;
            box-shadow: #a6e22e 2px 4px;
        }

        .admin_text {
            color: whitesmoke;
            margin-left: 80%;
            padding: 2px;
            border-radius: 4px;
            box-shadow: #1e7e34 2px 4px;
            border-bottom: 1px dashed darkblue;
        }

        .form_text {
            border-bottom: 2px solid #0c1923;
            border-radius: 5px;
            min-height: 10%;
            max-height: 200px;
            min-width: 20%;
            max-width: 35%;
            float: right;
            direction: rtl;
            text-align: center;
            padding-top: 15px;
        }

        .form_send_button {
            border-radius: 6px;
            height: 48px;
            margin: 2px;
            background-color: red;
            color: white;
            float: right;

        }

        .footer {
        {#border: 2px solid red;#} margin: 10px;
            height: 40px;
            width: 50%;
            margin: auto;
        }


    </style>
</head>
<body>

<header class="header">

    <h1> Hello Dear {{ user.username }} {{ time|time:"H:i" }}</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="alert alert-{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

</header>


<div class="content">

    <div class="content_holder">

        <div class="user">
            <img> {{ user.username }}
        </div>

        <div class="admin">
            <img src="{% static 'img/iconA.png' %}"> admin
        </div>


        <div class="text_holder">
            <p class="user_text "> {{ contact.user_text }}</p>
            <br>
        </div>

        <form class="user_form" action="{% url 'contactus:admin_answer_contact' contact.id %}" method="POST">
            {% csrf_token %}
            <textarea class="form_text " name="admin_text" placeholder=".............type here"></textarea>
            <button class=" form_send_button"> {% trans 'send' %}</button>
            <input name="is_new" type="hidden" value="False"/>
        </form>

    </div>

    <div class="data-form">
    </div>

</div>


<footer class="footer"></footer>

</body>
</html>

contactus/templates/contactus/contact_us.html
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{% static 'img/iconA.png' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/iconA.png' %}">

    <title>{% trans 'contact us' %}</title>

    <style>
        body {
            text-align: center;

        }

        .header {
            margin-bottom: 10px;
            color: white;
        }

        .header > h1 {
            background-color: #0f74a8;
            border-radius: 10px;
            padding: 4px;

        }

        .header > ul {
            list-style: none;
        }

        .header > .alert {
            color: red;
        }

        .header > .alert-success {
            color: red !important;
        }

        .header > .alert-error {
            color: orangered;
        }

        #home:hover {
            scale: 1.3;
            color: red;
        }

        #home{
            background-color:#6e6b5e;
            display: inline-block;
            color: white;
            border-radius: 8px;
            width: 80px;
            height: 30px;
            text-decoration:none;
            text-align:center;
            padding-top: 10px;
        }


        .content {
            min-height: 500px;
            width: 50%;
            margin: 0 auto;
            border-radius: 5px;
            box-shadow: 0 0 10px;
            padding-top: 8px;
            background-image: url({% static 'img/WallpapersNew.jpg' %});
        }

        .content_holder {
            padding:2px 4px;
            box-shadow: #0E2231 0 0 10px;
            margin:auto ;
            width: 90%;
            min-height: 500px;
            color: white !important;
            overflow: hidden;
            border-radius: 3px;
            font-size:22px;
        }

        .content_holder > .user {
            float: right;
            width: 25%;
            height: 40px;
            text-align: center;
            padding-top: 10px;
            border-radius: 2px 2px 2px 20px;
            {#background-color: #76d02c;#}
            margin-bottom: 20px;
            border-bottom: 2px solid  black;
            color: red;
        }

        .content_holder > .admin {
            color: orangered;
            border: 0 solid transparent;
            float: left;
            width: 20%;
            height: 40px;
            text-align: center;
            padding-top: 10px;
            border-radius: 2px 2px 20px 2px;
            {#background-color: #1e7e34;#}
            border-bottom: 2px solid  black;

        }

        .text_holder {
            border: 2px solid transparent;
            margin-top: 15%;
            font-size: 21px;
            width: 100%;
            min-height: 500px;
        }

        .user_text{
            color:black;
            margin-left:80%;
            border-bottom:1px dashed darkblue ;
            padding: 2px;
            border-radius: 4px;
            box-shadow: #a6e22e 2px 4px;
        }

        .admin_text{
            color:whitesmoke;
            margin-right:80%;
            padding: 2px;
            border-radius: 4px;
            box-shadow: #1e7e34 2px 4px;
            border-bottom:1px dashed darkblue ;
        }

        .form_text {
            border-bottom: 2px solid #0c1923;
            border-radius: 5px;
            min-height: 10%;
            max-height: 200px;
            min-width: 20%;
            max-width: 35%;
            float: right;
            direction: rtl;
            text-align: center;
            padding-top: 15px;
        }

        .form_send_button {
            border-radius: 6px;
            height: 48px;
            margin:2px ;
            background-color: red;
            color: white;
            float: right;

        }

        .footer {
            margin: 10px;
            height: 40px;
            width:50%;
            margin: auto;
        }



    </style>
</head>
<body>

<header class="header">
    {{ value|time:"H:i" }}
    <h1> Hello Dear {{ user.username }} , Here You Can Say Us What You Need </h1>
    <a id="home" href="{% url 'shop:product_list' %}"> HOME </a>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="alert alert-{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

</header>


<div class="content">

    <div class="content_holder">

        <div class="user">
            <img> {{ user.username }}
        </div>

        <div class="admin">
            <img src="{% static 'img/iconA.png' %}"> admin
        </div>


        <div class="text_holder">
            {% for text in contact %}
                <p class="user_text "> {{ text.user_text }}</p>
                <br>
                <p class="admin_text "> {{ text.admin_text}}</p>
            {% endfor %}
        </div>


        <form class="user_form" action="{% url 'contactus:user_to_admin_contact' %}" method="POST">
            {% csrf_token %}
                        <textarea class="form_text " name="user_text" placeholder=".............type here"></textarea>

            <button class=" form_send_button"> {% trans 'send' %}</button>
        </form>
    </div>

    <div class="data-form">
    </div>
<a href="{% url 'shop:product_list' %}"> Home </a>
</div>


<footer class="footer">
    <a href="{% url 'shop:product_list' %}"> Home </a>
</footer>

</body>
</html>

contactus/templates/contactus/user_new_contact.html
{% extends '_base.html' %}
{% load i18n %}

{% block content %}
    <p class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2"> " {{ contact|length }} " : user message to answer </p>
<br>
    <ul class="messages">

        {% for new_contact in contact %}
            <li class="alert alert-success ">
                <a class="btn btn-fullwidth btn-bg btn-color-red btn-hover-2" href="{% url 'contactus:admin_answer_contact' new_contact.id %}">{{ new_contact.user }} </a>
            </li>
        {% endfor %}

    </ul>

    <br>
    <br>

    <p class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2"> " {{ admin_awareness|length }} " : products get empty of quantity  </p>
    <br>
    <ul class="messages">
        {% for new_awar in admin_awareness %}

            <li class=" alert alert-success ">
            <form action="{% url 'shop:admin_awareness_check' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="admin_awareness_id" value="{{ new_awar.id}}">
                <input type="hidden" name="product_id" value="{{ new_awar.access_way}}">
                <button class="btn btn-fullwidth btn-bg btn-color-red btn-hover-2" type="submit">{{ new_awar.subject }} </button>
            </form>

{#                <a href="{% url 'shop:product_detail'  %}"> </a>#}
            </li>
        {% endfor %}
    </ul>
{% endblock %}